### ISSUE TITLE
Typo in get.aggregated.profile?

### ISSUE THREAD

**Issue by halterc** [carmonalab/HiTME#7]
In get.aggregated.profile there is a part where names are assigned to columns (for cell types). (see reference to code section below)
If I understand correctly:
The first part handles the case if there are multiple cell types. (?)
The second part if there is only one cell type.

Can't this be handled by a general loop, valid for ncol >=1 ?
I.e. like this

`     for(av in names(avg.exp)){ 
       colnames(avg.exp[[i]]) <- 
         unique(object@meta.data[!is.na(object@meta.data[[group.by.aggregated[[i]]]]), 
                                 group.by.aggregated[[i]]]) 
     } `

Alternatively, shouldn't the first line read:

`   if(ncol(avg.exp[[i]]) > 1){
`
?

https://github.com/carmonalab/HiTME/blob/d1514aca82926b89695e396c143003622bcec67a/R/main.R#L717-L731

**Comment by JGarnica22** [comment]
Thank you for that. This has been fixed.
