### ISSUE TITLE
compatibility with lower version of R

### ISSUE THREAD

**Issue by NoemieL** [carmonalab/HiTME#8]
Hello,

I am very interested in using your tools which seems great for cell classification. However I am currently using R version 4.1.3 and HiTME requires R >= 4.3.1. Would it be possible to make it compatible with a lower version of R?

Thanks

Noemie

**Comment by JGarnica22** [comment]
Hi Noemie, 

Thank you very much for your interest in our work. Unfortunately, we are not planning to accommodate our tools for earlier versions of R in the short term.

However, if you want to stick to R 4.1.3 for consistency in your analysis, you can still work with multiple R version in the same terminal. Please see here for [guidance](https://bioinformatics.ccr.cancer.gov/docs/rtools/R%20and%20RStudio/2.6_switching_r_version/). We also highly recommend using [renv package](https://rstudio.github.io/renv/articles/renv.html)  to help you to create reproducible environments and keep track of R and packages versions.

Bests,

Josep
